import { promises as fs } from 'fs';
import path from 'path';
import fetch from 'node-fetch';

const __filename = new URL(import.meta.url).pathname;
const __dirname = path.dirname(__filename);

const gptStatusFile = path.resolve(__dirname, "../gpt4o_status.json");
const ELEVENLABS_API_KEY = 'sk_f5e46959e592f2f421fcfd3de377da4c0019e60dc2b46672';
const ELEVENLABS_VOICE_ID = 'JBFqnCBsd6RMkjVDRZzb';

const apiUrls = [
  "https://api.siputzx.my.id/api/ai/deepseek-llm-67b-chat?content=",
  "https://vapis.my.id/api/gpt4o?q=",
  "https://vapis.my.id/api/gemini?q=",
  "https://vapis.my.id/api/luminai?q="
];

async function isOwner(msg, conn) {
  const botNumber = conn.user.id.split(':')[0].replace(/\D/g, '');
  const senderNumber = msg.sender.split(':')[0].replace(/\D/g, '');
  return senderNumber === botNumber;
}

async function readGptStatus() {
  try {
    const content = await fs.readFile(gptStatusFile, 'utf-8');
    return JSON.parse(content);
  } catch {
    return { enabled: false };
  }
}

async function writeGptStatus(status) {
  try {
    await fs.writeFile(gptStatusFile, JSON.stringify({ enabled: status }, null, 2));
  } catch (err) {
    console.error('Error writing GPT status:', err);
  }
}

async function sendTTSMessage(conn, msg, text) {
  try {
    const audioRes = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${ELEVENLABS_VOICE_ID}`, {
      method: 'POST',
      headers: {
        'xi-api-key': ELEVENLABS_API_KEY,
        'Content-Type': 'application/json',
        'Accept': 'audio/mpeg'
      },
      body: JSON.stringify({
        text: text,
        model_id: "eleven_multilingual_v2",
        voice_settings: {
          stability: 0.4,
          similarity_boost: 0.75
        }
      })
    });

    if (audioRes.ok) {
      const audioBuffer = await audioRes.buffer();
      await conn.sendMessage(msg.from, {
        audio: audioBuffer,
        mimetype: 'audio/mpeg',
        ptt: true,
        contextInfo: {
          externalAdReply: {
            title: "AI Voice Response",
            body: "Generated by cloud ai",
            thumbnailUrl: "https://files.catbox.moe/pimw8h.jpg",
            mediaType: 1,
            showAdAttribution: true,
            sourceUrl: "https://vapis.my.id"
          }
        }
      }, { quoted: msg });
    } else {
      console.error("TTS request failed.");
    }
  } catch (err) {
    console.error("TTS error:", err);
  }
}

const deepseek = async (msg, conn) => {
  const gptStatus = await readGptStatus();
  const text = msg.body.trim();

  if (text.toLowerCase() === "deepseek on" || text.toLowerCase() === "deepseek off") {
    if (!(await isOwner(msg, conn))) {
      await conn.sendMessage(msg.from, { text: "❌ Only the owner can toggle AI." }, { quoted: msg });
      return;
    }
    const enable = text.toLowerCase() === "deepseek on";
    await writeGptStatus(enable);
    await conn.sendMessage(msg.from, { text: `✅ AI has been ${enable ? "activated" : "deactivated"}.` }, { quoted: msg });
    return;
  }

  if (!gptStatus.enabled) return;

  await msg.react('💻');

  let reply = null;

  for (const baseUrl of apiUrls) {
    try {
      const response = await fetch(baseUrl + encodeURIComponent(text));
      if (!response.ok) {
        console.error(`API failed: ${baseUrl}, status: ${response.status}`);
        continue;
      }

      const json = await response.json();
      reply = json.data || json.message;
      if (reply) break;

    } catch (err) {
      console.error(`Error with API ${baseUrl}:`, err);
      continue;
    }
  }

  if (!reply) {
    await conn.sendMessage(msg.from, { text: "❌ All AI APIs failed. Please try again later." }, { quoted: msg });
    await msg.react('❌');
    return;
  }

  // Send text reply
  await conn.sendMessage(msg.from, { text: reply }, { quoted: msg });

  // Send TTS audio of reply
  await sendTTSMessage(conn, msg, reply);

  await msg.react('✅');
};

export default deepseek;
